name: Update dataset

on:
  schedule:
    # Update Thu 04:15 (CST) per week
    - cron: "15 20 * * 3"
  workflow_dispatch: {}

jobs:
  update_dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: |
          sudo apt install -y lua5.3
          sudo npm install -g pnpm

      - run: pnpm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: |
          pnpm rebuild
          pnpm run --if-present prepare

      - name: Build & Validate
        run: |
          node to-esm.js
          bash scripts/buildAndValidate.sh

      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "noreply@outv.im"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "feat: update dataset"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
